name: macOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        archives: 'qtsvg qtbase qttools'
        cache: 'true'
    
    - name: Build
      run: |
        qmake
        make -j5

    - name: Create Basic DMG
      run: |
        mkdir WordSearchCreator-1.2-Basic/
        mkdir WordSearchCreator-1.2-Basic/WordSearchCreator.app/
        cp -r WordSearchCreator.app/ WordSearchCreator-1.2-Basic/WordSearchCreator.app/
        hdiutil create -volname "WordSearchCreator 1.2" -srcfolder WordSearchCreator-1.2-Basic -ov -format UDZO WordSearchCreator-1.2-Basic.dmg

    - name: Archive Basic DMG
      uses: actions/upload-artifact@v4
      with:
       name: basic-dmg
       path: WordSearchCreator-1.2-Basic.dmg

    - name: Create Deployable App Bundle
      run: |
        macdeployqt WordSearchCreator.app

    - name: Create Deployable DMG
      run: |
        mkdir WordSearchCreator-1.2/
        mkdir WordSearchCreator-1.2/WordSearchCreator.app/
        cp -r WordSearchCreator.app/ WordSearchCreator-1.2/WordSearchCreator.app/
        hdiutil create -volname "WordSearchCreator 1.2" -srcfolder WordSearchCreator-1.2 -ov -format UDZO WordSearchCreator-1.2.dmg

    - name: Archive Deployable DMG
      uses: actions/upload-artifact@v4
      with:
       name: deployable-dmg
       path: WordSearchCreator-1.2.dmg
