name: macOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: Install Qt
      run: brew install qt@5
    - uses: actions/checkout@v3
    - name: Build
      run: |
        PATH="/usr/local/opt/qt@5/bin:$PATH"
        LDFLAGS="-L/usr/local/opt/qt@5/lib"
        CPPFLAGS="-I/usr/local/opt/qt@5/include"
        qmake
        make -j5
