name: Ubuntu 22.04 Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev libqt5svg5-dev
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake
    - name: make
      run: make -j5
    - name: Archive compiled binary
      uses: actions/upload-artifact@v4
      with:
       name: binary
       path: wordsearchcreator
