name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        archives: 'x86_64 qtsvg qtbase'
        cache: 'true'
    - uses: actions/checkout@v3
    
    - name: qmake
      run: qmake
      
    - name: make
      run: make -j5
      
    - name: Archive compiled binary
      uses: actions/upload-artifact@v4
      with:
       name: binary
       path: release/wordsearchcreator.exe
       
    - name: Collect Dlls
      run: |
         mkdir dist\plugins\platforms\
         cp .\release\wordsearchcreator.exe .\dist\
         cp ..\Qt\5.15.2\mingw81_64\bin\Qt5Gui.dll .\dist\
         cp ..\Qt\5.15.2\mingw81_64\bin\Qt5Core.dll .\dist\
         cp ..\Qt\5.15.2\mingw81_64\bin\Qt5Network.dll .\dist\
         cp ..\Qt\5.15.2\mingw81_64\bin\Qt5Widgets.dll .\dist\
         cp ..\Qt\5.15.2\mingw81_64\bin\Qt5PrintSupport.dll .\dist\
         cp ..\Qt\5.15.2\mingw81_64\bin\Qt5Svg.dll .\dist\
         cp ..Qt\5.15.2\mingw81_64\bin\Qt5Xml.dll .\dist\
         cp C:\mingw64\bin\libgcc_s_seh-1.dll .\dist\
         cp C:\mingw64\bin\libstdc++-6.dll .\dist\
         cp C:\mingw64\bin\libwinpthread-1.dll .\dist\
         cp ..\Qt\5.15.2\mingw81_64\plugins\platforms\qwindows.dll .\dist\plugins\platforms\
         cp .\fonts\*.ttf .\dist\

    - name: Archive dist directory
      uses: actions/upload-artifact@v4
      with:
       name: dist
       path: dist
